<a href="https://colab.research.google.com/github/sakshi2215/Machine_learning/blob/main/assignment_lecture4.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Use the following dataset - https://www.kaggle.com/lakshmi25npathi/imdb-dataset-of-50k-movie-reviews

In [60]:
# Problem 1

# Apply all the preprocessing techniques that you think are necessary
import pandas as pd
import numpy as np
df= pd.read_csv('/content/IMDB Dataset.csv')
df.head()

review sentiment
0  One of the other reviewers has mentioned that ...  positive
1  A wonderful little production. <br /><br />The...  positive
2  I thought this was a wonderful way to spend ti...  positive
3  Basically there's a family where a little boy ...  negative
4  Petter Mattei's "Love in the Time of Money" is...  positive

In [61]:
###BASIC PREPROCESSING ###
import re
#Lowercasing the letters
df['review']= df['review'].str.lower()

#Removing html Tags
def remove_tags(text):
  pattern = re.compile('<.*?>')
  return pattern.sub(r'',text)
df['review']= df['review'].apply(remove_tags)

#Remove any url
def remove_url(text):
  pattern = re.compile(r'https?://\S+|www\.\S+')
  return pattern.sub(r'',text)
df['review'] = df['review'].apply(remove_url)

#Removing the punctuation
import string
string.punctuation
exclude = string.punctuation

def remove_punc(text):
  for char in exclude:
    text= text.replace(char, '')
  return text
df['review'] = df['review'].apply(remove_punc)



In [62]:
##MAIN PREPROCESSING STEP
import nltk
from textblob import TextBlob
from nltk.corpus import stopwords
nltk.download('stopwords')
nltk.download('punkt')
from nltk.stem.porter import PorterStemmer
from nltk.tokenize import word_tokenize

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Package punkt is already up-to-date!


In [63]:

stop = stopwords.words('english')
df['review']= df['review'].apply(lambda x: ' '.join([word for word in x.split() if word not in stop]))
df

review sentiment
0      one reviewers mentioned watching 1 oz episode ...  positive
1      wonderful little production filming technique ...  positive
2      thought wonderful way spend time hot summer we...  positive
3      basically theres family little boy jake thinks...  negative
4      petter matteis love time money visually stunni...  positive
...                                                  ...       ...
49995  thought movie right good job wasnt creative or...  positive
49996  bad plot bad dialogue bad acting idiotic direc...  negative
49997  catholic taught parochial elementary schools n...  negative
49998  im going disagree previous comment side maltin...  negative
49999  one expects star trek movies high art fans exp...  negative

[50000 rows x 2 columns]

In [64]:
# Problem 2

# Find out the number of words in the entire corpus and also the total number of unique words(vocabulary) using just python
corpus=[]
unique_corpus= set()
for review in df['review']:
  words = review.split()
  corpus.extend(words)
  unique_corpus.update(words)



In [39]:
corpus

['one',
 'reviewers',
 'mentioned',
 'watching',
 '1',
 'oz',
 'episode',
 'youll',
 'hooked',
 'right',
 'exactly',
 'happened',
 'methe',
 'first',
 'thing',
 'struck',
 'oz',
 'brutality',
 'unflinching',
 'scenes',
 'violence',
 'set',
 'right',
 'word',
 'go',
 'trust',
 'show',
 'faint',
 'hearted',
 'timid',
 'show',
 'pulls',
 'punches',
 'regards',
 'drugs',
 'sex',
 'violence',
 'hardcore',
 'classic',
 'use',
 'wordit',
 'called',
 'oz',
 'nickname',
 'given',
 'oswald',
 'maximum',
 'security',
 'state',
 'penitentary',
 'focuses',
 'mainly',
 'emerald',
 'city',
 'experimental',
 'section',
 'prison',
 'cells',
 'glass',
 'fronts',
 'face',
 'inwards',
 'privacy',
 'high',
 'agenda',
 'em',
 'city',
 'home',
 'manyaryans',
 'muslims',
 'gangstas',
 'latinos',
 'christians',
 'italians',
 'irish',
 'moreso',
 'scuffles',
 'death',
 'stares',
 'dodgy',
 'dealings',
 'shady',
 'agreements',
 'never',
 'far',
 'awayi',
 'would',
 'say',
 'main',
 'appeal',
 'show',
 'due',
 'f

In [40]:
print(len(unique_corpus))

222430


In [41]:
print(len(corpus))


5992609


In [65]:
# Problem 3
import sklearn as sns
# Apply One Hot Encoding
new_df = pd.get_dummies(df, columns=['sentiment',],drop_first=True)
new_df

# next_df = pd.get_dummies(df,columns=['review',])


review  sentiment_positive
0      one reviewers mentioned watching 1 oz episode ...                True
1      wonderful little production filming technique ...                True
2      thought wonderful way spend time hot summer we...                True
3      basically theres family little boy jake thinks...               False
4      petter matteis love time money visually stunni...                True
...                                                  ...                 ...
49995  thought movie right good job wasnt creative or...                True
49996  bad plot bad dialogue bad acting idiotic direc...               False
49997  catholic taught parochial elementary schools n...               False
49998  im going disagree previous comment side maltin...               False
49999  one expects star trek movies high art fans exp...               False

[50000 rows x 2 columns]

In [43]:
# Problem 4

# Apply bag words and find the vocabulary also find the times each word has occured
from sklearn.feature_extraction.text import CountVectorizer
vectorizer = CountVectorizer(analyzer = "word",   \
                             tokenizer = None,    \
                             preprocessor = None, \
                             stop_words = None,   \
                             max_features = 5000)
X = vectorizer.fit_transform(new_df['review'][:5000])


In [44]:
vectorizer.get_feature_names_out()

array(['10', '100', '1000', ..., 'zombie', 'zombies', 'zone'],
      dtype=object)

In [45]:
vectorizer.vocabulary_

{'one': 3121,
 'reviewers': 3700,
 'mentioned': 2821,
 'watching': 4827,
 'oz': 3168,
 'episode': 1517,
 'youll': 4989,
 'hooked': 2164,
 'right': 3716,
 'exactly': 1565,
 'happened': 2039,
 'first': 1748,
 'thing': 4466,
 'struck': 4260,
 'scenes': 3839,
 'violence': 4764,
 'set': 3926,
 'word': 4938,
 'go': 1931,
 'trust': 4619,
 'show': 3984,
 'pulls': 3473,
 'regards': 3598,
 'drugs': 1381,
 'sex': 3934,
 'hardcore': 2046,
 'classic': 820,
 'use': 4710,
 'called': 644,
 'given': 1921,
 'maximum': 2784,
 'security': 3882,
 'state': 4186,
 'focuses': 1778,
 'mainly': 2720,
 'city': 811,
 'section': 3881,
 'prison': 3415,
 'glass': 1925,
 'face': 1628,
 'high': 2115,
 'em': 1461,
 'home': 2155,
 'muslims': 2966,
 'irish': 2362,
 'death': 1149,
 'never': 3018,
 'far': 1664,
 'would': 4957,
 'say': 3826,
 'main': 2719,
 'appeal': 275,
 'due': 1389,
 'fact': 1633,
 'goes': 1937,
 'shows': 3991,
 'wouldnt': 4958,
 'dare': 1122,
 'forget': 1807,
 'pretty': 3396,
 'pictures': 3275,
 'painte

In [46]:
df_bow_sklearn = pd.DataFrame(X.toarray())
df_bow_sklearn.head()

0     1     2     3     4     5     6     7     8     9     ...  4990  \
0     0     0     0     0     0     0     0     0     0     0  ...     0   
1     0     0     0     0     0     0     0     0     0     0  ...     0   
2     0     0     0     0     0     0     0     0     0     0  ...     1   
3     1     0     0     0     0     0     0     0     0     0  ...     0   
4     0     0     0     0     0     0     0     0     0     0  ...     0   

   4991  4992  4993  4994  4995  4996  4997  4998  4999  
0     0     0     0     0     0     0     0     0     0  
1     0     0     0     0     0     0     0     0     0  
2     0     0     0     0     0     0     0     0     0  
3     0     1     0     0     0     0     1     0     0  
4     0     0     0     0     0     0     0     0     0  

[5 rows x 5000 columns]

In [47]:
# Problem 5

# Apply bag of bi-gram and bag of tri-gram and write down your observation about the dimensionality of the vocabulary
vectorizer2 = CountVectorizer(analyzer = "word",   \
                             tokenizer = None,    \
                             preprocessor = None, \
                             stop_words = None,   \
                             max_features = 5000,
                             ngram_range=(2,2))
X2 = vectorizer2.fit_transform(df['review'][:5000])
vectorizer2.get_feature_names_out()

array(['10 10', '10 lines', '10 minutes', ..., 'youve seen',
       'zombie movie', 'zombie movies'], dtype=object)

In [48]:
print(X2.toarray())
print(X2.toarray().shape)
print(vectorizer2.vocabulary_)

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
(5000, 5000)
{'first thing': 1530, 'sex violence': 3949, 'would say': 4914, 'due fact': 905, 'first episode': 1501, 'ever saw': 1043, 'graphic violence': 1848, 'order get': 3289, 'get away': 1620, 'middle class': 2657, 'extremely well': 1111, 'well worth': 4752, 'worth watching': 4851, 'one great': 3198, 'little things': 2402, 'well done': 4725, 'way spend': 4713, 'spend time': 4067, 'serial killer': 3932, 'woody allen': 4812, 'many us': 2609, 'dare say': 751, 'ive never': 2124, 'great comedy': 1858, 'go see': 1723, 'little boy': 2387, 'soap opera': 4021, 'youre going': 4990, 'going make': 1742, 'make film': 2531, 'film must': 1345, 'like real': 2352, 'real life': 3604, 'movie instead': 2823, 'time money': 4409, 'visually stunning': 4608, 'film watch': 1430, 'human relations': 2041, 'movie seems': 2892, 'telling us': 4236, 'new york': 3082, 'one way': 3269, 'way anoth

In [49]:
vectorizer3 = CountVectorizer(analyzer = "word",   \
                             tokenizer = None,    \
                             preprocessor = None, \
                             stop_words = None,   \
                             max_features = 5000,
                             ngram_range=(3,3))
X2 = vectorizer3.fit_transform(df['review'][:5000])
vectorizer3.get_feature_names_out()

array(['10 lines text', '10 minutes film', '10 year old', ...,
       'youre looking movie', 'youve never seen', 'zombies come back'],
      dtype=object)

In [51]:
vectorizer3.vocabulary_

{'well worth watching': 4700,
 'way spend time': 4684,
 'suspected serial killer': 4189,
 'decade ive never': 770,
 'devil wears prada': 810,
 'youre going make': 4995,
 'going make film': 1795,
 'like real life': 2475,
 'love time money': 2570,
 'one way another': 3348,
 'alltime favorite movie': 141,
 'never gets old': 3132,
 'brings tears eyes': 462,
 'makes fun watch': 2718,
 'would like see': 4890,
 'would bring back': 4857,
 'believe ive got': 315,
 'complete waste time': 658,
 'find hard believe': 1565,
 'truly one worst': 4427,
 'almost every way': 151,
 'like movie young': 2467,
 'low budget film': 2584,
 'didnt care much': 821,
 '12 year old': 4,
 'im big fan': 2089,
 'dont really know': 971,
 'mad scientist dr': 2604,
 'go see movie': 1774,
 'ten lines text': 4224,
 'going say movie': 1797,
 'another good thing': 188,
 'good thing movie': 1860,
 'man constant sorrow': 2739,
 'film ive ever': 1471,
 'ive ever seen': 2163,
 'like high school': 2446,
 'high school film': 1984,


In [81]:
# Problem 6

# Apply tf-idf and find out the idf scores of words, also find out the vocabulary.
from sklearn.feature_extraction.text import TfidfVectorizer
vectorizer = TfidfVectorizer(analyzer = "word",   \
                             max_features = 1000)
X = vectorizer.fit_transform(df['review'][:5000])
vectorizer.get_feature_names_out()
print(X.toarray())

[[0.         0.         0.         ... 0.         0.         0.        ]
 [0.         0.         0.         ... 0.         0.         0.        ]
 [0.         0.         0.         ... 0.         0.         0.        ]
 ...
 [0.         0.         0.         ... 0.         0.         0.        ]
 [0.         0.         0.07607512 ... 0.         0.         0.        ]
 [0.         0.         0.         ... 0.         0.         0.        ]]


In [82]:
vectorizer.idf_

array([3.6709544 , 5.00653366, 4.69711161, 4.90227265, 4.67320608,
       4.01613496, 3.71830052, 4.27564616, 4.19927318, 4.7988943 ,
       2.59770932, 3.47002099, 3.66806839, 2.95494908, 4.26511974,
       4.47396805, 3.00416306, 4.46114737, 4.78119472, 5.18665983,
       4.34690918, 4.34124344, 4.95304498, 4.88266418, 5.37425845,
       4.92227332, 3.21660738, 4.39342919, 3.65946002, 4.02845545,
       2.41324908, 3.45360796, 3.27128641, 4.189517  , 4.83526194,
       3.68258243, 4.53378655, 5.18665983, 4.87300227, 4.33560962,
       3.04659367, 3.41483458, 3.2147742 , 4.50011333, 4.81691281,
       4.48044057, 4.73826968, 4.93242569, 4.53378655, 4.93242569,
       4.44221936, 5.24072705, 3.11381897, 4.4114477 , 5.00653366,
       4.74670855, 4.19927318, 4.78119472, 4.47396805, 3.64809626,
       4.82604529, 4.65758077, 4.69711161, 3.35829778, 4.99560459,
       3.86140136, 5.08657637, 2.9409236 , 4.92227332, 2.45263414,
       4.90227265, 5.25471329, 3.86490399, 4.92227332, 4.45479

In [83]:
vectorizer.vocabulary_

{'one': 607,
 'mentioned': 546,
 'watching': 945,
 'episode': 259,
 'youll': 995,
 'right': 716,
 'exactly': 273,
 'happened': 386,
 'first': 322,
 'thing': 865,
 'scenes': 736,
 'violence': 930,
 'set': 761,
 'word': 971,
 'go': 366,
 'show': 772,
 'sex': 765,
 'classic': 147,
 'use': 915,
 'called': 117,
 'given': 362,
 'city': 145,
 'face': 285,
 'high': 401,
 'home': 408,
 'death': 193,
 'never': 586,
 'far': 298,
 'would': 981,
 'say': 731,
 'main': 520,
 'due': 229,
 'fact': 286,
 'goes': 368,
 'shows': 775,
 'wouldnt': 982,
 'forget': 332,
 'pretty': 671,
 'audiences': 60,
 'doesnt': 219,
 'mess': 547,
 'around': 52,
 'ever': 268,
 'saw': 730,
 'couldnt': 168,
 'watched': 944,
 'got': 373,
 'kill': 461,
 'order': 612,
 'get': 354,
 'away': 63,
 'well': 951,
 'middle': 550,
 'class': 146,
 'turned': 900,
 'lack': 472,
 'street': 827,
 'experience': 281,
 'may': 535,
 'become': 79,
 'side': 776,
 'wonderful': 969,
 'little': 503,
 'production': 678,
 'gives': 363,
 'sometimes': 79

In [84]:
y= pd.DataFrame(X.toarray())

In [85]:
y

0    1         2    3    4    5    6        7    8    9    ...  \
0     0.000000  0.0  0.000000  0.0  0.0  0.0  0.0  0.00000  0.0  0.0  ...   
1     0.000000  0.0  0.000000  0.0  0.0  0.0  0.0  0.00000  0.0  0.0  ...   
2     0.000000  0.0  0.000000  0.0  0.0  0.0  0.0  0.00000  0.0  0.0  ...   
3     0.121689  0.0  0.000000  0.0  0.0  0.0  0.0  0.00000  0.0  0.0  ...   
4     0.000000  0.0  0.000000  0.0  0.0  0.0  0.0  0.00000  0.0  0.0  ...   
...        ...  ...       ...  ...  ...  ...  ...      ...  ...  ...  ...   
4995  0.000000  0.0  0.000000  0.0  0.0  0.0  0.0  0.00000  0.0  0.0  ...   
4996  0.000000  0.0  0.000000  0.0  0.0  0.0  0.0  0.00000  0.0  0.0  ...   
4997  0.000000  0.0  0.000000  0.0  0.0  0.0  0.0  0.12281  0.0  0.0  ...   
4998  0.000000  0.0  0.076075  0.0  0.0  0.0  0.0  0.00000  0.0  0.0  ...   
4999  0.000000  0.0  0.000000  0.0  0.0  0.0  0.0  0.00000  0.0  0.0  ...   

           990       991  992  993       994       995       996       997  \
0     0.000000  0.000000  0.0  0.0  0.000000  0.096591  0.000000  0.000000   
1     0.000000  0.000000  0.0  0.0  0.000000  0.000000  0.000000  0.000000   
2     0.000000  0.123876  0.0  0.0  0.000000  0.000000  0.137644  0.000000   
3     0.000000  0.000000  0.0  0.0  0.000000  0.000000  0.000000  0.125012   
4     0.000000  0.000000  0.0  0.0  0.127046  0.000000  0.000000  0.000000   
...        ...       ...  ...  ...       ...       ...       ...       ...   
4995  0.000000  0.000000  0.0  0.0  0.000000  0.000000  0.000000  0.000000   
4996  0.093172  0.142881  0.0  0.0  0.000000  0.000000  0.000000  0.000000   
4997  0.000000  0.000000  0.0  0.0  0.000000  0.000000  0.000000  0.000000   
4998  0.000000  0.000000  0.0  0.0  0.000000  0.000000  0.000000  0.000000   
4999  0.000000  0.000000  0.0  0.0  0.000000  0.000000  0.000000  0.000000   

      998      999  
0     0.0  0.00000  
1     0.0  0.00000  
2     0.0  0.00000  
3     0.0  0.17763  
4     0.0  0.00000  
...   ...      ...  
4995  0.0  0.00000  
4996  0.0  0.00000  
4997  0.0  0.00000  
4998  0.0  0.00000  
4999  0.0  0.00000  

[5000 rows x 1000 columns]

In [77]:
print(X.toarray()[50])

[0. 0. 0. ... 0. 0. 0.]
