<a href="https://colab.research.google.com/github/sakshi2215/Machine_learning/blob/main/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Numpy**- Numerical Python, for scientific calculation .

1.   Python library that provides a multidimensional array object, various derived Objects.
2.   It contains information about the raw data, how to locate an element, and how to interpret an element.




**Advantages of list**consumes less memory, fast as compared to list and convenient to use.
**Uses**- mathematical, logical, shape manipulation, sorting, selecting,I/O, discrete fourier transformations, basic linear algebra

In [1]:
import numpy as np

In [4]:
x= np.array([1,2,3,4])
print (x)
print(type(x))

[1 2 3 4]
<class 'numpy.ndarray'>


In [5]:
y=[1,2,3,4]
print(y)
print(type(y))

[1, 2, 3, 4]
<class 'list'>


In [6]:
%timeit [j**4 for j in range(1,9)]

3.51 µs ± 865 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [8]:
%timeit np.arange(1,9)**4

3.95 µs ± 939 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [10]:
l=[]
for i in range(1,5):
  int_l= int(input("enter :"))
  l.append(int_l)
print(np.array(l))

enter :34
enter :56
enter :67
enter :56
[34 56 67 56]


**Zero**

In [14]:
arr_zero = np.zeros(4)
print(arr_zero)
arr1_zero= np.zeros((3,4))
print(arr1_zero)

[0. 0. 0. 0.]
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


**Ones** **array**

In [15]:
arr_one = np.ones(4)
print(arr_one)

[1. 1. 1. 1.]


**Empty Array**   **np.eye() *function* for diagonal array- Identity**

In [17]:
arr_empty= np.empty(4)
print(arr_empty)

[1. 1. 1. 1.]


**Linspace**

In [20]:

arr_lin = np.linspace(0,10,num=4)
print(arr_lin)

[ 0.          3.33333333  6.66666667 10.        ]



1.   rand()
2.   randn()
3.   randf()
4.   randint()



In [22]:
random_values = np.random.rand(3, 3)  # Generates a 3x3 array of random values between 0 and 1
random_values

array([[0.41494265, 0.94783303, 0.82103347],
       [0.14970831, 0.74392013, 0.38023105],
       [0.67344896, 0.16539457, 0.56587428]])

In [23]:
random_values = np.random.randn(3, 3)  # Generates a 3x3 array of random values from a standard normal distribution
random_values

array([[ 0.68249471, -1.46848663, -0.13554769],
       [ 0.04087463,  0.48003719,  1.15062141],
       [-1.74024757,  0.76382303, -0.30889517]])

In [25]:
random_integer = np.random.randint(1, 10,7)  # Generates a random integer between 1 (inclusive) and 10 (exclusive)
random_integer

array([1, 9, 4, 7, 2, 5, 2])

**dtype**

**Arithmatic Operation in Numpy**

In [26]:
import numpy as np

# Create two arrays for demonstration
array1 = np.array([[1, 2], [3, 4]])
array2 = np.array([[5, 6], [7, 8]])

# Addition
result_addition = np.add(array1, array2)

# Subtraction
result_subtraction = np.subtract(array1, array2)

# Multiplication (element-wise)
result_multiplication = np.multiply(array1, array2)

# Division (element-wise)
result_division = np.divide(array1, array2)

# Matrix multiplication (dot product)
result_matrix_multiplication = np.dot(array1, array2)

# Transposition
transposed_array1 = np.transpose(array1)

# Element-wise square root
result_sqrt = np.sqrt(array1)

# Element-wise power
result_power = np.power(array1, 2)

# Element-wise absolute value
result_absolute = np.abs(array1)

# Sum along a specific axis
sum_along_axis = np.sum(array1, axis=0)

# Maximum and minimum values
max_value = np.max(array1)
min_value = np.min(array1)

# Print results
print("Array 1:\n", array1)
print("Array 2:\n", array2)
print("Addition:\n", result_addition)
print("Subtraction:\n", result_subtraction)
print("Multiplication (element-wise):\n", result_multiplication)
print("Division (element-wise):\n", result_division)
print("Matrix Multiplication:\n", result_matrix_multiplication)
print("Transposition:\n", transposed_array1)
print("Element-wise Square Root:\n", result_sqrt)
print("Element-wise Power (squared):\n", result_power)
print("Element-wise Absolute Value:\n", result_absolute)
print("Sum along axis 0:\n", sum_along_axis)
print("Maximum value:\n", max_value)
print("Minimum value:\n", min_value)


Array 1:
 [[1 2]
 [3 4]]
Array 2:
 [[5 6]
 [7 8]]
Addition:
 [[ 6  8]
 [10 12]]
Subtraction:
 [[-4 -4]
 [-4 -4]]
Multiplication (element-wise):
 [[ 5 12]
 [21 32]]
Division (element-wise):
 [[0.2        0.33333333]
 [0.42857143 0.5       ]]
Matrix Multiplication:
 [[19 22]
 [43 50]]
Transposition:
 [[1 3]
 [2 4]]
Element-wise Square Root:
 [[1.         1.41421356]
 [1.73205081 2.        ]]
Element-wise Power (squared):
 [[ 1  4]
 [ 9 16]]
Element-wise Absolute Value:
 [[1 2]
 [3 4]]
Sum along axis 0:
 [4 6]
Maximum value:
 4
Minimum value:
 1


In [27]:

# Create an array for demonstration
array = np.array([1, 2, 3, 4, 5])

# Cumulative sum- Calculates the cumulative sum of elements along a given axis.
cumulative_sum = np.cumsum(array)

# Element-wise square root
square_root = np.sqrt(array)

# Element-wise sine- Computes the element-wise sine of the array.
sine_values = np.sin(array)

# Element-wise cosine- Computes the element-wise cosine of the array.
cosine_values = np.cos(array)

# Print results
print("Original Array:\n", array)
print("Cumulative Sum:\n", cumulative_sum)
print("Element-wise Square Root:\n", square_root)
print("Element-wise Sine:\n", sine_values)
print("Element-wise Cosine:\n", cosine_values)


Original Array:
 [1 2 3 4 5]
Cumulative Sum:
 [ 1  3  6 10 15]
Element-wise Square Root:
 [1.         1.41421356 1.73205081 2.         2.23606798]
Element-wise Sine:
 [ 0.84147098  0.90929743  0.14112001 -0.7568025  -0.95892427]
Element-wise Cosine:
 [ 0.54030231 -0.41614684 -0.9899925  -0.65364362  0.28366219]


**Shape and Reshaping in array**

In [28]:

# Create an array
arr = np.array([[1, 2, 3], [4, 5, 6]])

# Get the shape of the array
arr_shape = arr.shape

print("Original Array:\n", arr)
print("Shape of the Array:", arr_shape)


Original Array:
 [[1 2 3]
 [4 5 6]]
Shape of the Array: (2, 3)


In [29]:

# Create a 1D array
arr_1d = np.array([1, 2, 3, 4, 5, 6])

# Reshape the array to a 2D array with 2 rows and 3 columns
arr_2d = arr_1d.reshape((2, 3))

print("Original 1D Array:", arr_1d)
print("Reshaped 2D Array:\n", arr_2d)

Original 1D Array: [1 2 3 4 5 6]
Reshaped 2D Array:
 [[1 2 3]
 [4 5 6]]


In [30]:
# Create a 1D array with 27 elements
arr_1d = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27])

# Reshape the 1D array into a 3D array with shape (3, 3, 3)
arr_3d = arr_1d.reshape((3, 3, 3))

print("Original 1D Array:", arr_1d)
print("Reshaped 3D Array:\n", arr_3d)


Original 1D Array: [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27]
Reshaped 3D Array:
 [[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[10 11 12]
  [13 14 15]
  [16 17 18]]

 [[19 20 21]
  [22 23 24]
  [25 26 27]]]
