<a href="https://colab.research.google.com/github/sakshi2215/Machine_learning/blob/main/Numpy2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Broadcastic in Numpy**

In [1]:
import numpy as np
var1 = np.array([1,2,3,4])
var2 = np.array([1,2,3])
print(var1+var2)

ValueError: operands could not be broadcast together with shapes (4,) (3,) 

In [4]:
num1= np.array([1,2,3])
num2=np.array([[1],[2],[3]])
print(num1.shape)
print(num1)
print()
print(num2.shape)
print(num2)
print()
print(num1+num2) #broadcasting

(3,)
[1 2 3]

(3, 1)
[[1]
 [2]
 [3]]

[[2 3 4]
 [3 4 5]
 [4 5 6]]


In [5]:
# Create a 2x1 array
arr_a = np.array([[1],
                  [2]])

# Create a 2x3 array
arr_b = np.array([[10, 20, 30],
                  [40, 50, 60]])

# Broadcasting: Add arr_a to each column of arr_b
result = arr_a + arr_b

print(result)   # Here, arr_a 2x1 and arr_b is 2x3 then, max of(2,2)=2 and max(1,3)=3
                #we move from left to right then result array is of dimension 3x2

[[11 21 31]
 [42 52 62]]


**Iterate Numpy Array** -- using nditer() function


In [2]:
# Create a 2x3 array
arr = np.array([[1, 2, 3],
                [4, 5, 6]])

# Using nditer to iterate over the elements
with np.nditer(arr, flags=['multi_index'], op_flags=['readwrite']) as it:
    for x in it:
        print(f"Element at {it.multi_index} is {x}")

# Alternatively, you can use nditer with a traditional for loop
for x in np.nditer(arr):
    print(x)

Element at (0, 0) is 1
Element at (0, 1) is 2
Element at (0, 2) is 3
Element at (1, 0) is 4
Element at (1, 1) is 5
Element at (1, 2) is 6
1
2
3
4
5
6


**copy vs view in numpy array**

In [3]:

# Copy:

# When you create a copy of an array, you get a new array with its own data.
# Changes made to the copy do not affect the original array, and vice versa.
# You explicitly use the copy() method to create a copy of the array.
arr = np.array([1, 2, 3])
arr_copy = arr.copy()

arr_copy[0] = 100

print(arr)       # Output: [1 2 3]
print(arr_copy)  # Output: [100 2 3]

[1 2 3]
[100   2   3]


In [4]:
# View:

# When you create a view of an array, you get a different way of looking at the same data.
# Changes made to the view affect the original array, and vice versa.
# # Views are created using slicing or using the view() method.
arr = np.array([1, 2, 3])
arr_view = arr[1:]

arr_view[0] = 200

print(arr)      # Output: [1 200 3]
print(arr_view) # Output: [200 3]

[  1 200   3]
[200   3]


**Join and Split in array**---numpy.concatenate, numpy.stack, and numpy.split functions are commonly used for joining and splitting arrays.

**Numpy array Function**-- Search, sort, search sorted, filter

In [5]:
# Create a NumPy array
arr = np.array([4, 2, 7, 1, 9, 5])

# Search for the index where the value 7 should be inserted to maintain sorted order
search_result = np.searchsorted(arr, 7)

# Sort the array
sorted_arr = np.sort(arr)

# Filter elements greater than 4
filtered_arr = arr[arr > 4]

# Print the results
print("Original Array:", arr)
print("Index to Insert 7:", search_result)
print("Sorted Array:", sorted_arr)
print("Filtered Array (Elements > 4):", filtered_arr)
# where in array

Original Array: [4 2 7 1 9 5]
Index to Insert 7: 6
Sorted Array: [1 2 4 5 7 9]
Filtered Array (Elements > 4): [7 9 5]


**Insert and Delete Function in numpy array**